### ISSUE TITLE
Please update to Circuitpython8

### ISSUE THREAD

**Issue by bobricius** [lyusupov/POST_TEcho#1]
It is look cool, no plans to update to new circuitpython version
or include build definitions to main branch?
Thanks very much.
I try yesterday all build for NRF on circuitpython.org page but no one works.

**Comment by lyusupov** [comment]
> no plans to update to new circuitpython version

No.

https://github.com/Xinyuan-LilyGO/lilygo-micropython/commit/23f950eba4df35bda09601ef6c85cbe703e9fec3
