### ISSUE TITLE
New Updates for Circuitpython 7 ? 

### ISSUE THREAD

**Issue by KenSamson** [lyusupov/POST_TEcho#2]
The idea of being able to run Circuitpython on this hardware platform with Lora support onboard is amazing...

As the libraries had to be compiled in...  I'm thinking it would take a lot of work to get Circuitpython 7 support for this board... but I thought I would at least ask if anyone was thinking of doing that?

Thank you very much for your time and this amazing work...

Ken

**Comment by lyusupov** [comment]
**Resolution:** duplicate ( https://github.com/lyusupov/POST_TEcho/issues/1 )
